### ISSUE TITLE
remove comment

### ISSUE THREAD

**Issue by MayaSasson** [chenFriedman/you-ate-it#40]
https://github.com/chenFriedman/you-ate-it/blob/1f430f2f6056ce78cedd8fe4933314b556807573/client/src/uAteIt/food-tab/food-tab.tsx#L8

**Comment by chenFriedman** [comment]
same as https://github.com/chenFriedman/you-ate-it/issues/16

**Comment by chenFriedman** [comment]
same as https://github.com/chenFriedman/you-ate-it/issues/16
