### ISSUE TITLE
Do you deal with a case that there was a value on else field and now it is cleared? does it show the form is invalid? same in line 77

### ISSUE THREAD

**Issue by MayaSasson** [chenFriedman/you-ate-it#42]
https://github.com/chenFriedman/you-ate-it/blob/1f430f2f6056ce78cedd8fe4933314b556807573/client/src/uAteIt/food-tab/food-tab.tsx#L90

**Comment by chenFriedman** [comment]
yes, in the submit function I delete it before sending the values

const submit = () => {
    if (isFormValid) {
      let temp: any = {foodFormState}
      if (foodFormState.else) {
        let tmpelseValue = newFoodOptionValue
        temp[tmpelseValue]=true  
      }
      delete temp.else;
      onSubmit(temp)
  } else {
    setShowErrorMsg(true)
  }
}
